apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "set a dockerconfigjson for ghrc" .Values.dockerconfigjson | b64enc | quote }}
